# Generated by Django 4.2.5 on 2023-12-14 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mechanics Name')),
                ('age', models.CharField(blank=True, max_length=50, null=True, verbose_name='AGE')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('identity_image', models.FileField(upload_to='mechanics_identity', verbose_name='Identity Image')),
                ('exp_cer_image', models.FileField(upload_to='mechanics_certificate', verbose_name='Experienced Certificate Image')),
                ('machanic_type', models.CharField(blank=True, default='Fresher', max_length=50, null=True, verbose_name='Machanics Type')),
                ('no_of_exper', models.CharField(blank=True, max_length=50, null=True, verbose_name='Experience')),
            ],
        ),
        migrations.CreateModel(
            name='add_new_cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_email', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_skype', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_vat_no', models.CharField(blank=True, max_length=15, null=True)),
                ('comp_type', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('phy_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_web', models.CharField(blank=True, max_length=100, null=True)),
                ('dir_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('dir_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dir_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_ref_1', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_ref_2', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_ref_3', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('notif', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_met', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_period', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_sal_disc', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='importExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='import_excel_files')),
            ],
        ),
        migrations.CreateModel(
            name='job_machanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50, verbose_name='Job Type')),
            ],
        ),
        migrations.CreateModel(
            name='machanic_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machanic_names', models.CharField(max_length=50, verbose_name='Machanic Name')),
            ],
        ),
        migrations.CreateModel(
            name='New_job_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('quotation_no', models.CharField(max_length=50, verbose_name='Quotation No.')),
                ('cust_addr', models.CharField(max_length=50, verbose_name='Customer Address.')),
                ('veh_reg_no', models.CharField(max_length=50, verbose_name='Vehical Registration No.')),
                ('cust_phone', models.CharField(max_length=50, verbose_name='Customer Phone No.')),
                ('cust_mobile', models.CharField(max_length=50, verbose_name='Customer Mobile No.')),
                ('cust_refer', models.CharField(max_length=50, verbose_name='Reference')),
                ('seh_time', models.CharField(max_length=50, verbose_name='Schedule_Date')),
                ('deliver_time', models.CharField(max_length=50, verbose_name='Delivery Date')),
                ('cust_note', models.CharField(max_length=50, verbose_name='Customer Details')),
                ('alert_via', models.CharField(max_length=50, verbose_name='Alert Via')),
                ('job_type', models.CharField(max_length=50, verbose_name='Job Type')),
                ('machanic_names', models.CharField(blank=True, max_length=50, null=True, verbose_name='Machanic Name')),
                ('notes', models.CharField(max_length=50, verbose_name='Customer Note')),
            ],
        ),
        migrations.CreateModel(
            name='quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=500, null=True)),
                ('quotation_no', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_addr', models.CharField(blank=True, max_length=500, null=True)),
                ('quot_date', models.DateField()),
                ('cust_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('veh_reg_no', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rates', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('items', models.CharField(blank=True, max_length=500, null=True)),
                ('availale_qty', models.CharField(blank=True, max_length=500, null=True)),
                ('qty', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('total_price', models.CharField(blank=True, max_length=500, null=True)),
                ('allTotal', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='User name')),
                ('user_email', models.CharField(max_length=50, verbose_name='User Email')),
                ('user_password', models.CharField(max_length=50, verbose_name='Password')),
                ('user_conf_pass', models.CharField(max_length=50, verbose_name='Confirm Password')),
            ],
        ),
        migrations.CreateModel(
            name='veh_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=500, null=True)),
                ('availale_qty', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_name', models.CharField(blank=True, max_length=50, null=True)),
                ('veh_year', models.IntegerField(blank=True, null=True)),
                ('veh_reg_date', models.DateField()),
                ('veh_reg_no', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 14, 23, 11, 30, 546586), null=True)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motors.add_new_cust', verbose_name='Vehicle Holding Name')),
            ],
        ),
    ]
