# Generated by Django 4.1.5 on 2023-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_new_cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_email', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_skype', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_vat_no', models.CharField(blank=True, max_length=15, null=True)),
                ('comp_type', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('phy_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_web', models.CharField(blank=True, max_length=100, null=True)),
                ('dir_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('dir_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dir_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_ref_1', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_ref_2', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_ref_3', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('notif', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_met', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_period', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_sal_disc', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
