# Generated by Django 4.1.5 on 2023-02-17 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_name', models.CharField(blank=True, max_length=50, null=True)),
                ('veh_year', models.IntegerField(blank=True, null=True)),
                ('veh_reg_date', models.DateField()),
                ('veh_reg_no', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.date(2023, 2, 17), null=True)),
            ],
        ),
    ]
