# Generated by Django 4.1.5 on 2023-02-20 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_vehicle_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 2, 20), null=True),
        ),
    ]
