# Generated by Django 4.1.5 on 2023-02-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0004_vehicle_details_fk_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_details',
            name='veh_cust_name',
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
