# Generated by Django 4.1.5 on 2023-02-22 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0005_remove_vehicle_details_veh_cust_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 15, 50, 55, 915882), null=True),
        ),
        migrations.CreateModel(
            name='quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotations_no', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('quo_date', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('fk_quo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.add_new_cust', verbose_name='Holding customer name')),
            ],
        ),
    ]
