# Generated by Django 4.1.5 on 2023-02-23 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0006_alter_vehicle_details_created_date_quotations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotations',
            old_name='quo_date',
            new_name='quot_date',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='details',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='fk_quo',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='quotations_no',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='quotations',
            name='cust_addr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='cust_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='cust_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='veh_reg_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 15, 53, 31, 351846), null=True),
        ),
    ]
