# Generated by Django 4.1.5 on 2023-02-27 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0007_rename_quo_date_quotations_quot_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rates', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 14, 23, 20, 87427), null=True),
        ),
    ]
