# Generated by Django 4.1.5 on 2023-02-27 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0008_job_card_alter_vehicle_details_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_card',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 14, 25, 23, 154171), null=True),
        ),
    ]
