# Generated by Django 4.1.5 on 2023-02-28 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0009_alter_job_card_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='veh_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=500, null=True)),
                ('availale_qty', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 28, 10, 57, 9, 654435), null=True),
        ),
    ]
