# Generated by Django 4.1.5 on 2023-02-28 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0010_veh_parts_alter_vehicle_details_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_vehicle_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=500, null=True)),
                ('availale_qty', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('total_price', models.CharField(blank=True, max_length=500, null=True)),
                ('allTotal', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 28, 15, 1, 33, 620163), null=True),
        ),
    ]
