# Generated by Django 4.1.5 on 2023-03-24 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0017_quotations_alltotal_quotations_availale_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_machanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50, verbose_name='Job Type')),
                ('machanic_name', models.CharField(max_length=50, verbose_name='Machanic Name')),
            ],
        ),
        migrations.DeleteModel(
            name='buy_vehicle_parts',
        ),
        migrations.DeleteModel(
            name='job_card',
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 24, 14, 33, 32, 691837), null=True),
        ),
    ]
