# Generated by Django 4.1.5 on 2023-03-24 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0019_machanic_name_remove_job_machanic_machanic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('quotations_no', models.CharField(max_length=50, verbose_name='Quotation No.')),
                ('cust_addr', models.CharField(max_length=50, verbose_name='Customer Address.')),
                ('veh_reg_no', models.CharField(max_length=50, verbose_name='Vehical Registration No.')),
                ('cust_Phone', models.CharField(max_length=50, verbose_name='Customer Phone No.')),
                ('cust_mobile', models.CharField(max_length=50, verbose_name='Customer Mobile No.')),
                ('cust_refer', models.CharField(max_length=50, verbose_name='Reference')),
                ('seh_time', models.CharField(max_length=50, verbose_name='Schedule_Date')),
                ('deliver_time', models.CharField(max_length=50, verbose_name='Delivery Date')),
                ('cust_note', models.CharField(max_length=50, verbose_name='Customer Details')),
                ('alert_via', models.CharField(max_length=50, verbose_name='Alert Via')),
                ('job_type', models.CharField(max_length=50, verbose_name='Job Type')),
                ('machanic_name', models.CharField(max_length=50, verbose_name='Machanic Name')),
                ('notes', models.CharField(max_length=50, verbose_name='Customer Note')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 24, 15, 39, 30, 845384), null=True),
        ),
    ]
