# Generated by Django 4.1.5 on 2023-03-24 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0021_alter_vehicle_details_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_order',
            old_name='machanic_name',
            new_name='machanic_names',
        ),
        migrations.RenameField(
            model_name='machanic_name',
            old_name='machanic_name',
            new_name='machanic_names',
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 24, 15, 55, 12, 111449), null=True),
        ),
    ]
