# Generated by Django 4.1.5 on 2023-03-27 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0022_rename_machanic_name_job_order_machanic_names_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_order',
            new_name='New_job_order',
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 11, 51, 52, 951167), null=True),
        ),
    ]
