# Generated by Django 4.1.5 on 2023-03-27 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0023_rename_job_order_new_job_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_job_order',
            old_name='cust_Phone',
            new_name='cust_phone',
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 12, 12, 6, 242643), null=True),
        ),
    ]
