# Generated by Django 4.1.5 on 2023-03-27 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0024_rename_cust_phone_new_job_order_cust_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_job_order',
            old_name='quotations_no',
            new_name='quotation_no',
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 12, 14, 37, 723309), null=True),
        ),
    ]
