# Generated by Django 4.1.5 on 2023-03-27 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0025_rename_quotations_no_new_job_order_quotation_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_job_order',
            name='machanic_names',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Machanic Name'),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 12, 28, 25, 89880), null=True),
        ),
    ]
