# Generated by Django 4.1.5 on 2023-03-27 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0026_alter_new_job_order_machanic_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 12, 31, 53, 957039), null=True),
        ),
    ]
