# Generated by Django 4.1.5 on 2023-03-30 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0027_alter_vehicle_details_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mechanics Name')),
                ('age', models.CharField(max_length=50, verbose_name='AGE')),
                ('mobile', models.CharField(max_length=50, verbose_name='Mobile')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('identity_image', models.FileField(upload_to='mechanics_identity', verbose_name='Identity Image')),
                ('exp_cer_image', models.FileField(upload_to='mechanics_certificate', verbose_name='Experienced Certificate Image')),
                ('machanic_type', models.CharField(max_length=50, verbose_name='Machanics Type')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 14, 49, 38, 139240), null=True),
        ),
    ]
