# Generated by Django 4.1.5 on 2023-03-30 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0028_add_mechanics_alter_vehicle_details_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_mechanics',
            name='no_of_exper',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 15, 4, 15, 542431), null=True),
        ),
    ]
