# Generated by Django 4.1.5 on 2023-03-31 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0029_add_mechanics_no_of_exper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 11, 22, 1, 229689), null=True),
        ),
    ]
