# Generated by Django 4.1.5 on 2023-04-03 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0031_alter_add_mechanics_machanic_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_mechanics',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='add_mechanics',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AGE'),
        ),
        migrations.AlterField(
            model_name='add_mechanics',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='add_mechanics',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mechanics Name'),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 10, 56, 39, 569540), null=True),
        ),
    ]
