# Generated by Django 4.1.5 on 2023-04-03 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0032_alter_add_mechanics_address_alter_add_mechanics_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_mechanics',
            name='machanic_type',
            field=models.CharField(max_length=50, verbose_name='Machanics Type'),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 11, 1, 37, 330664), null=True),
        ),
    ]
