# Generated by Django 4.1.5 on 2023-04-03 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0034_alter_add_mechanics_machanic_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_mechanics',
            name='machanic_type',
            field=models.CharField(blank=True, default='Fresher', max_length=50, null=True, verbose_name='Machanics Type'),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 11, 8, 57, 392719), null=True),
        ),
    ]
