# Generated by Django 4.1.5 on 2023-04-04 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0037_add_mechanics_machanic_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='User name')),
                ('user_email', models.CharField(max_length=50, verbose_name='User Email')),
                ('user_pass', models.CharField(max_length=50, verbose_name='Password')),
                ('user_conf_pass', models.CharField(max_length=50, verbose_name='Confirm Password')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 12, 18, 14, 744416), null=True),
        ),
    ]
