# Generated by Django 4.1.5 on 2023-04-04 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0038_user_login_alter_vehicle_details_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 14, 3, 56, 603644), null=True),
        ),
    ]
