# Generated by Django 4.1.5 on 2023-04-04 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0039_alter_vehicle_details_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_login',
            old_name='user_pass',
            new_name='user_password',
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 14, 6, 39, 385131), null=True),
        ),
    ]
